concourse-url: http://127.0.01:8080/ # e.g. http://192.168.100.4:8080/
concourse-team: main  # e.g. main
concourse-username: test  # e.g. admin
concourse-password: test
concourse-pipeline-name: simple-react-full-stack  # e.g. shipt-it-enhanced
github-access-token: 3b99743ae0831474c974383608ccda2d179e0bda