---
resources:
- name: send-email
  type: email
  source:
    from: gabriel@nunez.com
- name: commit
  type: git
  source:
    branch: master
    uri: https://github.com/gabcinder2004/devops_practice_1.git
jobs:
- name: Build App
  plan:
  - get: commit
    trigger: true
  - task: Build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
      inputs:
      - name: commit
      run:
        path: commit/pipeline/build-app.sh
      params:
        PORT: 3030
        API_URL: http://localhost:8080
- name: Build Image
  plan:
  - get: commit
    passed:
      - Build App
    trigger: true
  - task: Build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: docker
          tag: dind
      inputs:
      - name: commit
      run:
        path: commit/pipeline/build-image.sh
- name: Run Tests
  plan:
  - get: commit
    passed:
      - Build Image
    trigger: true
  - task: do-your-test-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Output of test job. It gets automatically triggered after a successful Build-it job."
  - task: prep-email-text
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      inputs:
        - name: commit
      outputs:
        - name: email-text
      run:
        path: sh
        args:
        - -exc
        - |
          export LATEST_GOOD_VERSION=$(cat ./commit/version)
          echo "Version $LATEST_GOOD_VERSION is ready to ship!" >  ./email-text/email-subject.txt
          echo "Version $LATEST_GOOD_VERSION is ready to ship! For details, see pipeline {{ BUILD_PIPELINE_NAME }}, build {{ BUILD_NAME }}, job {{ BUILD_JOB_NAME }}." >  ./email-text/email-body.txt
  - put: send-email
    params:
      to: [gabcinder2004@yahoo.com]
      subject: ./email-text/email-subject.txt
      body: ./email-text/email-body.txt
- name: Deploy
  plan:
  - get: commit
    passed:
      - Run Tests
    trigger: false
  - task: do-your-shipit-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Output of your manually triggered Ship-it task."
resource_types:
  - name: email
    type: docker-image
    source:
      repository: mdomke/concourse-email-resource